export const GET_BOOK_BY_CATEGORY_REQUEST = 'GET_BOOK_BY_CATEGORY_REQUEST';
export const GET_BOOK_BY_CATEGORY_SUCCESS = 'GET_BOOK_BY_CATEGORY_SUCCESS';
export const GET_BOOK_BY_CATEGORY_FAILURE = 'GET_BOOK_BY_CATEGORY_FAILURE';

export const FILTER_BOOK_REQUEST = 'FILTER_BOOK_REQUEST';
export const FILTER_BOOK_SUCCESS = 'FILTER_BOOK_SUCCESS';
export const FILTER_BOOK_FAILURE = 'FILTER_BOOK_FAILURE';

export const GET_BOOK_BY_ID_REQUEST = 'GET_BOOK_BY_ID_REQUEST';
export const GET_BOOK_BY_ID_SUCCESS = 'GET_BOOK_BY_ID_SUCCESS';
export const GET_BOOK_BY_ID_FAILURE = 'GET_BOOK_BY_ID_FAILURE';

export const FIND_BOOK_BY_NAME_REQUEST = 'FIND_BOOK_BY_NAME_REQUEST';
export const FIND_BOOK_BY_NAME_SUCCESS = 'FIND_BOOK_BY_NAME_SUCCESS';
export const FIND_BOOK_BY_NAME_FAILURE = 'FIND_BOOK_BY_NAME_FAILURE';

export const GET_LATEST_BOOK_REQUEST = 'GET_LATEST_BOOK_REQUEST';
export const GET_LATEST_BOOK_SUCCESS = 'GET_LATEST_BOOK_SUCCESS';
export const GET_LATEST_BOOK_FAILURE = 'GET_LATEST_BOOK_FAILURE';

export const GET_HOT_BOOK_REQUEST = 'GET_HOT_BOOK_REQUEST';
export const GET_HOT_BOOK_SUCCESS = 'GET_HOT_BOOK_SUCCESS';
export const GET_HOT_BOOK_FAILURE = 'GET_HOT_BOOK_FAILURE';

export const GET_FAVORITE_BOOK_REQUEST = 'GET_FAVORITE_BOOK_REQUEST';
export const GET_FAVORITE_BOOK_SUCCESS = 'GET_FAVORITE_BOOK_SUCCESS';
export const GET_FAVORITE_BOOK_FAILURE = 'GET_FAVORITE_BOOK_FAILURE';
