export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

export const PAYMENT_SUCCESS_REQUEST = 'PAYMENT_SUCCESS_REQUEST';
export const PAYMENT_SUCCESS_SUCCESS = 'PAYMENT_SUCCESS_SUCCESS';
export const PAYMENT_SUCCESS_FAILURE = 'PAYMENT_SUCCESS_FAILURE';

export const PAYMENT_COD_REQUEST = 'PAYMENT_COD_REQUEST';
export const PAYMENT_COD_SUCCESS = 'PAYMENT_COD_SUCCESS';
export const PAYMENT_COD_FAILURE = 'PAYMENT_COD_FAILURE';

