export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE';

export const GET_USER_ORDER_HISTORY_REQUEST = 'GET_USER_ORDER_HISTORY_REQUEST';
export const GET_USER_ORDER_HISTORY_SUCCESS = 'GET_USER_ORDER_HISTORY_SUCCESS';
export const GET_USER_ORDER_HISTORY_FAILURE = 'GET_USER_ORDER_HISTORY_FAILURE';

export const CANCEL_USER_ORDER_REQUEST = 'CANCEL_USER_ORDER_REQUEST';
export const CANCEL_USER_ORDER_SUCCESS = 'CANCEL_USER_ORDER_SUCCESS';
export const CANCEL_USER_ORDER_FAILURE = 'CANCEL_USER_ORDER_FAILURE';

export const GET_PENDING_ORDER_REQUEST = 'GET_PENDING_ORDER_REQUEST';
export const GET_PENDING_ORDER_SUCCESS = 'GET_PENDING_ORDER_SUCCESS';
export const GET_PENDING_ORDER_FAILURE = 'GET_PENDING_ORDER_FAILURE';

export const GET_CONFIRMED_ORDER_REQUEST = 'GET_CONFIRMED_ORDER_REQUEST';
export const GET_CONFIRMED_ORDER_SUCCESS = 'GET_CONFIRMED_ORDER_SUCCESS';
export const GET_CONFIRMED_ORDER_FAILURE = 'GET_CONFIRMED_ORDER_FAILURE';

export const GET_SHIPPING_ORDER_REQUEST = 'GET_SHIPPING_ORDER_REQUEST';
export const GET_SHIPPING_ORDER_SUCCESS = 'GET_SHIPPING_ORDER_SUCCESS';
export const GET_SHIPPING_ORDER_FAILURE = 'GET_SHIPPING_ORDER_FAILURE';

export const GET_DELIVERED_ORDER_REQUEST = 'GET_DELIVERED_ORDER_REQUEST';
export const GET_DELIVERED_ORDER_SUCCESS = 'GET_DELIVERED_ORDER_SUCCESS';
export const GET_DELIVERED_ORDER_FAILURE = 'GET_DELIVERED_ORDER_FAILURE';

export const GET_PACKED_ORDER_REQUEST = 'GET_PACKED_ORDER_REQUEST';
export const GET_PACKED_ORDER_SUCCESS = 'GET_PACKED_ORDER_SUCCESS';
export const GET_PACKED_ORDER_FAILURE = 'GET_PACKED_ORDER_FAILURE';

export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST';
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS';
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE';

export const PACKED_ORDER_REQUEST = 'PACKED_ORDER_REQUEST';
export const PACKED_ORDER_SUCCESS = 'PACKED_ORDER_SUCCESS';
export const PACKED_ORDER_FAILURE = 'PACKED_ORDER_FAILURE';

export const SHIPPING_ORDER_REQUEST = 'SHIPPING_ORDER_REQUEST';
export const SHIPPING_ORDER_SUCCESS = 'SHIPPING_ORDER_SUCCESS';
export const SHIPPING_ORDER_FAILURE = 'SHIPPING_ORDER_FAILURE';

export const DELIVERED_ORDER_REQUEST = 'DELIVERED_ORDER_REQUEST';
export const DELIVERED_ORDER_SUCCESS = 'DELIVERED_ORDER_SUCCESS';
export const DELIVERED_ORDER_FAILURE = 'DELIVERED_ORDER_FAILURE';

export const GET_ALL_DELIVERED_ORDER_REQUEST = 'GET_ALL_DELIVERED_ORDER_REQUEST';
export const GET_ALL_DELIVERED_ORDER_SUCCESS = 'GET_ALL_DELIVERED_ORDER_SUCCESS';
export const GET_ALL_DELIVERED_ORDER_FAILURE = 'GET_ALL_DELIVERED_ORDER_FAILURE';
